#################################################################################
################################# Agreement #####################################
#################################################################################
# Authors
# Azadeh Hassanpour, azadeh.hassanpour@uni-goettingen.de
# Johannes Geibel, johannes.geibel@fli.de
# Torsten Pook, Torsten.pook@wur.nl
# Copyright © 2020 – 2024
# This program falls under a NonCommercial-NoDerivates-NoDistriubtion Public License.
# With use of these scripts, I confirm that I represent an academic institute and acknowledge that I shall use this script only for research. I explicitly acknowledge the terms in the license agreement https://github.com/AHassanpour88/Evolutionary_Snakemake/blob/main/License.md. I understood that any commercial use needs a commercial license from the owner of the script. For more information about a commercial license please contact Torsten Pook.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#################################################################################
#################################################################################
#################################################################################

# How many parameters we want to optimize?
nfactors: 4

# Do we have binary/class variables?
binary_parameter: TRUE
number_binary_parameter: 1
binary: [FALSE, FALSE, FALSE, TRUE]

# Which parameters should be integer??
integer: [TRUE, TRUE, TRUE, TRUE]

# Name of parameters we want to optimize?
name_parameter:
  - "n_test" 
  - "n_bull"
  - "n_bull_sel"
  - "MIR"

# number of initial simulation that we need to sample from can be specified within the sampleScript 
sim_init: 600 #big enough that we have a good coverage on search space!
sampleScript: "scripts/sampleScript.r"
# adapt your silumation script in simuScript
simuScript: "scripts/simuScript.r"
# Evolutionary algorithm 
evoScript: "scripts/evoScript.r"
evoParams: "config/iterations.csv"
# plotting a new points
visualizeParameters: "scripts/visualizeParameters.r"
# time in minuites (calculations are evaluated in script)
time: 1*1*60
# memory in Mb (calculations are evaluated in script)
memory: 5*1000 

# minimum range of mutation if the variation was low depends on the range of parameter
min_range_mut:  [40, 20, 3, 0.01]

# mutation probability of offspring
mut_offspring: 0.2
#mutation probability of parents
mut_parent: 0.3

# initial cost of the program to be calculated based on each parameter
# Only parameters that are included in cost functions will be used and then
# initial cost of the program to be calculated based on each parameter
# In this toy example as the cost is as constraint does not really matter the value of x1:x4 as long as the x_1(4000 + 1000x_4) + 3000x_2 - 10000000 < 0 is statisfied
# this is more important in larger breeding program that alternative scenarios compare to the current breeding program and cost is included in objective function
# Check the cost function in the Functions folder
base_cost_ini: [2368, 175 ,19 ,0]

# The binary variables and linked parameters are not included in rounding in light of the constraints
# These parameters will be used so that after sampling and generating offspring from scratch we stay within the budget
cost_par: [1,2]

# If you have linked parameters the evolutionary algorithm needs to be adapted based on the number of parameters, if there is additional adjustment to the is needed
# As an example you want to optimze the number of new parents for the next cycle and you have specific criteria from which cohorts parents should be selected and 
# if the number of those cohorts suppose to be optimized as well, you need to create a criteria that the number of units you are selecting from those cohorts are match the number of new parents!
# Find the linked_parameter if statement in the evoScript and adapt the number of parameters linked to your specific problem
linked_parameter: TRUE
linked_parameter_adjustment: FALSE 

################# Hybrid ##########################
Hybrid_Breeding: TRUE
linked_parameter_male:  [2, 1] # the fisrt parameter is the one that other parameters are after that linked to
linked_parameter_female: [1, 2] 
num_linked_parameter_male: 1
num_linked_parameter_female: 1
cheapest_unit_female: [1]
cheapest_unit_male: [2]

# Cheapest cost of a parameter using the cost function in Function folder
cost_cheapest_male: 3000
cost_cheapest_female: 4000

#################### Line ##########################
Line_Breeding: FALSE
num_linked_parameter: 0
which_linked_parameter:  [0, 0]
cheapest_unit: [0]
cost_cheapest: 0

# For visualization, if you already know what is your target is
my_target: TRUE
target: [2368, 175, 19, 0]


